-- Baseline schema. Creates everything the app has: the auth tables (`users`,
-- `oauth_accounts`, `auth_sessions`) and the roadmap Phase 1b inventory domain
-- (`categories`, `inventory_items`, `inventory_events`, `mandates`).
--
-- SQUASHED HISTORY. This replaces four migrations, three of which existed only
-- to build and then dismantle the removed chat app:
--
--   0000_init              created `sessions` + `messages`
--   0001_auth_users_oauth  created the auth tables AND altered `sessions`
--   0002_drop_chat         dropped `sessions` + `messages` again
--   0003_inventory_domain  created the inventory domain
--
-- A fresh database therefore created two tables, altered one of them, and then
-- dropped both — pure churn on every new deployment, and a history that read as
-- if chat were still part of the system. Squashing was safe because no database
-- had applied them: the deployment record confirmed nothing needed preserving.
-- The chat app's removal is still documented in docs/ARCHITECTURE.md and
-- docs/PRD.md; it just no longer costs a deployment two dead tables.
--
-- If a database HAD applied the old chain, this would not have been safe: the
-- migrator keys on a hash of each file, so a rewritten baseline reads as
-- unapplied and re-runs, failing on CREATE TABLE against tables that exist.
--
-- Machine-generated (drizzle-kit 0.31.10), then renamed from its random tag to
-- `0000_init` (matching drizzle/meta/_journal.json) and given this header. Not
-- idempotent — 0.31 emits plain CREATE TABLE rather than IF NOT EXISTS — which
-- is the safer failure, since a silent no-op is how a migration can appear to
-- succeed while changing nothing. Once applied anywhere, do not edit this file:
-- the migrator records a hash of its contents.
--
-- Three things are deliberate and will look wrong against docs/PRD.md §6:
--
--  1. `inventory_items` has NO `par_level` / `restock_level`. They live on
--     `mandates` instead (decisions D1 + D4 in docs/context/INVENTORY_CONTEXT.md).
--     A book and a carton of eggs are both complete rows here; "is this
--     reorderable?" is answered by whether a `mandates` row exists, which is one
--     FK the database enforces rather than a nullable-column convention every
--     consumer has to remember. The PRD is knowingly stale on this until its
--     Chunk 8 reconciliation pass.
--  2. `mandates` has UNIQUE (inventory_item_id) and no `active` column. One rule
--     per item — revising a rule is an UPDATE, not a second row — and pause/resume
--     is out of scope by decision, which is what `active` existed for.
--  3. `mandates.grant_id` is absent, not forgotten: its FK target `grants` does
--     not exist yet, and adding a nullable FK column in Phase 2 is purely additive.
--
-- Quantities are `integer`, not the fractional value PRD §5.1 describes (D5):
-- `unit` is free text and carries the granularity, so half a dozen eggs is
-- `6 x each`, not `0.5 x dozen`.
--
-- The `lower("name")` in the categories unique index is load-bearing: it is what
-- makes a second "Groceries" a 409 instead of a row. Unlike users.email, the name
-- is stored with the casing the user typed, so the index does the folding rather
-- than a normalise-on-write rule in the repository.

CREATE TABLE "auth_sessions" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"refresh_token_hash" text NOT NULL,
	"user_agent" text,
	"ip" text,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "oauth_accounts" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"provider" text NOT NULL,
	"provider_account_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"password_hash" text,
	"display_name" text,
	"avatar_url" text,
	"email_verified" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inventory_events" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"inventory_item_id" uuid NOT NULL,
	"delta" integer,
	"new_stock" integer NOT NULL,
	"reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inventory_items" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"category_id" uuid NOT NULL,
	"unit" text,
	"quantity" integer,
	"attributes" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mandates" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"inventory_item_id" uuid NOT NULL,
	"par_level" integer NOT NULL,
	"restock_level" integer,
	"trigger_condition" jsonb,
	"shopping_query" text,
	"preferred_product" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "auth_sessions" ADD CONSTRAINT "auth_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_accounts" ADD CONSTRAINT "oauth_accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inventory_events" ADD CONSTRAINT "inventory_events_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inventory_events" ADD CONSTRAINT "inventory_events_inventory_item_id_inventory_items_id_fk" FOREIGN KEY ("inventory_item_id") REFERENCES "public"."inventory_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mandates" ADD CONSTRAINT "mandates_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mandates" ADD CONSTRAINT "mandates_inventory_item_id_inventory_items_id_fk" FOREIGN KEY ("inventory_item_id") REFERENCES "public"."inventory_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "auth_sessions_refresh_token_hash_unique" ON "auth_sessions" USING btree ("refresh_token_hash");--> statement-breakpoint
CREATE INDEX "auth_sessions_user_id_idx" ON "auth_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "oauth_accounts_provider_account_unique" ON "oauth_accounts" USING btree ("provider","provider_account_id");--> statement-breakpoint
CREATE INDEX "oauth_accounts_user_id_idx" ON "oauth_accounts" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_unique" ON "users" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "categories_user_id_name_unique" ON "categories" USING btree ("user_id",lower("name"));--> statement-breakpoint
CREATE INDEX "inventory_events_user_id_created_at_idx" ON "inventory_events" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "inventory_events_item_id_created_at_idx" ON "inventory_events" USING btree ("inventory_item_id","created_at");--> statement-breakpoint
CREATE INDEX "inventory_items_user_id_name_idx" ON "inventory_items" USING btree ("user_id","name");--> statement-breakpoint
CREATE INDEX "inventory_items_category_id_idx" ON "inventory_items" USING btree ("category_id");--> statement-breakpoint
CREATE UNIQUE INDEX "mandates_inventory_item_id_unique" ON "mandates" USING btree ("inventory_item_id");--> statement-breakpoint
CREATE INDEX "mandates_user_id_idx" ON "mandates" USING btree ("user_id");